# enable Docker for your repository
options:
  docker: true
pipelines:
    default:
        - step:
            script:
                - echo "This script runs on all branches that don't have any specific pipeline assigned on branches'."
    tags:
        release-stage-*:
                - step:
                    name: Deploy to Stage
                    image: tstrohmeier/awscli:3.6.4
                    script:
                        # aws login
                        - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
                        # docker
                        - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
                        - docker build -t ${AWS_REGISTRY_URL}:$BUILD_ID ./aqu
                        - docker push ${AWS_REGISTRY_URL}:$BUILD_ID
                        - docker tag ${AWS_REGISTRY_URL}:$BUILD_ID ${AWS_REGISTRY_URL}:${BITBUCKET_TAG}
                        - docker push ${AWS_REGISTRY_URL}:${BITBUCKET_TAG}